apiVersion: v1
kind: ConfigMap
metadata:
  name: usuarios-config
data:
  usuarios.json: |
    [
      { "id": 1, "nombre": "Ana", "saldo": 100 },
      { "id": 2, "nombre": "Luis", "saldo": 150 }
    ]
