apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
      - name: usuarios
        image: usuarios-service:latest
        imagePullPolicy: Never  # ¡Importante! No intentes descargar la imagen
        env:
        - name: DATA_PATH
          value: /data/usuarios.json
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shared-data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-svc
spec:
  selector:
    app: usuarios
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---